# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  GOPATH: /opt/go
  PATH: /opt/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GO_VER: 1.18.10

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: ${{ env.GO_VER }}
      - name: Prepare Env
        run: bash scripts/prepare_environ.sh
      - name: Test
        working-directory: /home/runner/go/src/github.com/SmartBFT-Go/consensus
        run: make all
      - name: Post
        working-directory: /home/runner/go/src/github.com/SmartBFT-Go/consensus
        run: ./scripts/post.sh
